"""Byte-identical UI gate for the Companion Adapter shell-swap (Spec G · G4, #142).

The migration re-plumbs the live playground's *shell* onto ``langfuse-synth-core``'s
Companion Adapter (invocation/bind/health/secret-intake + ready Langfuse/LLM clients) and
must not move a single presenter-visible byte (story 13, 31 — "re-plumb the shell, never
bend the Surface"). These committed goldens are that fence: they capture the rendered output
of every presenter-visible route — the loan-application index and the ``/analytics``
in-scene dashboard — in both the bare and the ``LIVE_BASE_PATH``-prefixed serving mode, and
fail on any diff.

Discipline mirrors the kit's spool golden (``tests/golden/ev_spool.ndjson``): a committed
byte oracle plus a render-here-and-compare check, extending the render-twice-and-compare
pattern already in ``test_live_base_path.py``. The analytics dashboard is fully
deterministic — every figure is derived from the seeded plan (``build_series``), not a live
Langfuse read — so a fixed ``RunState`` + fixed run date + the shipped seed reproduce it
exactly. To re-bless after an *intended* surface change, delete ``tests/golden/ui/`` and
re-run ``scripts``-free: the fixtures are regenerated by this module's ``_render`` helper.
"""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

import pytest

GOLDEN = Path(__file__).parent / "golden" / "ui"

# Pinned identically to the spool golden / determinism anchors so the backdated series is
# reproducible (``tests/golden_seed.py``, ``tests/test_dashboard.py``).
RUN_DATE = datetime(2026, 6, 9, 12, 0, 0, tzinfo=timezone.utc)

# Fixed, non-secret connection identity so the dashboard's "open in Langfuse" deep link
# renders to a stable string in the golden.
STATE_BASE_URL = "https://demo.langfuse.example"
STATE_PROJECT_ID = "clproj0000demo0001"


def _seed_state() -> None:
    """Persist a RunState so ``/analytics`` renders the full dashboard (not the "no report
    yet" placeholder). Only ``run_date`` / ``project_id`` / ``base_url`` reach the render;
    the remaining fields complete the dataclass and are inert here."""
    from synth.state import RunState

    RunState(
        base_url=STATE_BASE_URL,
        project_name="demo",
        run_date=RUN_DATE.isoformat(),
        grant_effective_date="2026-06-02",
        drift_window="2026-06-04 → 2026-06-09",
        drift_window_days=5,
        prompt_name="credit_decision",
        prompt_versions={"production": 1, "development": 2},
        dataset_name="ev-grant-disputed-rejections",
        dataset_items=24,
        judge_model="claude-sonnet-4-6",
        task_model="claude-sonnet-4-6",
        grant_amount_eur=6000,
        price_cap_eur=50000,
        project_id=STATE_PROJECT_ID,
    ).save()


def _render(monkeypatch, tmp_path, base_path: str | None) -> dict[str, str]:
    """Render ``/`` and ``/analytics`` in the given serving mode; return ``{route: html}``.

    ``base_path`` None → bare serving (env unset); a string → that ``LIVE_BASE_PATH``."""
    from fastapi.testclient import TestClient

    from synth.config import load_config
    from synth.live import app as evapp

    monkeypatch.setenv("SYNTH_STATE_DIR", str(tmp_path))
    _seed_state()

    if base_path is None:
        monkeypatch.delenv("LIVE_BASE_PATH", raising=False)
    else:
        monkeypatch.setenv("LIVE_BASE_PATH", base_path)

    cfg = load_config("config/demo.yaml")
    cfg.generation.total_traces = 800  # matches the blessed fixtures (test_dashboard volume)
    client = TestClient(evapp.create_app(cfg))
    return {"index": client.get("/").text, "analytics": client.get("/analytics").text}


@pytest.mark.parametrize(
    "mode, base_path, route, filename",
    [
        ("bare", None, "index", "index.bare.html"),
        ("bare", None, "analytics", "analytics.bare.html"),
        ("prefixed", "/live/x", "index", "index.prefixed.html"),
        ("prefixed", "/live/x", "analytics", "analytics.prefixed.html"),
    ],
)
def test_presenter_output_byte_identical(monkeypatch, tmp_path, mode, base_path, route, filename):
    """Every presenter-visible route is byte-identical to its committed golden, before and
    after the shell-swap. Any diff fails the gate."""
    pytest.importorskip("fastapi")
    rendered = _render(monkeypatch, tmp_path, base_path)[route]
    golden = (GOLDEN / filename).read_text()
    assert rendered == golden, (
        f"{route} ({mode}) drifted from tests/golden/ui/{filename}; the shell-swap must not "
        f"move a presenter-visible byte (Spec G · G4 story 13/31)."
    )


def test_analytics_full_dashboard_and_prefix_present():
    """Guard the fixtures themselves: the analytics golden is the *full* dashboard (not the
    placeholder), and the prefixed variant actually carries the ``/live/x`` prefix — so the
    byte-identical assertions above are testing the real presenter surface, not an empty one."""
    assert "weekly risk report" in (GOLDEN / "analytics.bare.html").read_text()
    assert "/live/x/" in (GOLDEN / "analytics.prefixed.html").read_text()
    assert 'action="/submit"' in (GOLDEN / "index.bare.html").read_text()
    assert 'action="/live/x/submit"' in (GOLDEN / "index.prefixed.html").read_text()
